#!/usr/local/bin/bash

# dmenu translate script.
# Dependencies: xclip, trans, xsetroot, dmenu+patches.

# Function to show a message in the root window.
showmsg () {
    while true; do
        xsetroot -name "   TRANSLATION IN PROGRESS...     "
        sleep 0.5
    done
}
# Run the showmsg function in the background and store its process ID.
(showmsg) &
subsh_showmsg_pid=$!

# Set the maximum number of lines for display.
lines_max=50

# Get the selected text from the clipboard.
selected_text=$(xclip -o)

# Check if the clipboard is empty.
if [ -z "$selected_text" ]; then
    #echo "Clipboard is empty."
    exit 1
fi

# Translate the selected text to Ukrainian and format it.
translated_text=$(trans :uk -brief -no-pager <<< "$selected_text" 2> /dev/null | fold -w 80 -s)

# Kill the background process that was displaying the "TRANSLATION IN PROGRESS..." message.
kill $subsh_showmsg_pid

# Determine the number of lines in the translated text and limit it to the maximum.
line_number=$(wc -l <<< "$translated_text")
if [ $line_number -gt $lines_max ]; then
    line_number=$lines_max
fi

# Check if the translation is successful
if [ -z "$translated_text" ]; then
    #echo "Translation failed or not available for the selected text."
    exit 1
fi

# Display the translated text using dmenu with specified colors and window position.
echo "$translated_text" | dmenu -x 30 -y 50 -z 720 -nf "#FFD66A" -nb "#222222" -sb "#222222" -l $line_number

